version: "3.2"

volumes:
  es_data:
    driver: local
  pgadmin_data:
    driver: local
  pg_data:
    driver: local
  kibana_data:
    driver: local

networks:
  elastic:
    driver: bridge

services:

  app:
    image: go-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    ports:
      - 8015:8010
    container_name: go_app
    restart: unless-stopped
    networks:
      - elastic

  db:
    image: postgres:13.2-alpine
    hostname: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 6432:5432
    container_name: go_db
    restart: unless-stopped
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: "TestPassw0rd!"
      POSTGRES_USER: "postgres"
    networks:
      - elastic

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: go_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "TestPassw0rd!"
    depends_on:
      - db
    ports:
      - 6433:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - elastic

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es
    environment:
      - "discovery.type=single-node"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kib:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kib
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: '["http://es:9200"]'
    networks:
      - elastic